" → init plug plugin
  source $HOME/dotfiles/vim/plug.vimrc


"  general settings
  syntax on
  set backspace=2
  set nocompatible
  colorscheme gravy
  set background=dark
  set ttyfast termguicolors
  set splitbelow splitright
  set foldmethod=indent foldenable foldlevelstart=1
  set rnu number numberwidth=5
  set laststatus=2 showcmd noshowmode
  set cursorline scrolloff=9 nostartofline

  set encoding=utf-8
  set hidden autoread
  set ambiwidth=double
  set virtualedit=block
  set timeout updatetime=100 ttimeoutlen=20
  set clipboard^=unnamed,unnamedplus

  set linebreak
  set showbreak=˜
  set fillchars=""
  set autoindent copyindent
  filetype plugin indent on
  set wrap whichwrap+=<,>,[,]
  set shiftround shiftwidth=2
  set tabstop=2 softtabstop=2 expandtab

  set path+=**
  set gdefault
  set showmatch
  set completeopt=longest,menuone
  set ignorecase hlsearch incsearch
  set omnifunc=syntaxcomplete#Complete
  set wildmenu wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.pdf,*/Music/*,*/Pictures/*

  set viminfo+=n~/.vim/tmp/viminfo
  set backup backupdir=~/.vim/tmp/backup//
  set directory=~/.vim/tmp/swap// directory+=.
  set undofile undodir=~/.vim/tmp/undo undodir+=.


"  gvim settings
  if has('gui_running')
    set go=af ghr=0
    set linespace=4
    set mousehide mousemodel=popup mouse=a
    set guifont=Fantasque\ Sans\ Mono\ 16
  endif


"  netrw obviously
  let g:netrw_banner = 0
  let g:netrw_winsize = 25
  let g:netrw_dirhistmax = 0
  let g:netrw_liststyle = 3


"  source other vim settings
  source /home/angelo/dotfiles/vim/keys.vimrc
  source /home/angelo/dotfiles/vim/nerd.vimrc
  source /home/angelo/dotfiles/vim/lightline.vimrc
  source /home/angelo/dotfiles/vim/autocommands.vimrc
  source /home/angelo/dotfiles/vim/plugin-settings.vimrc

